#!/usr/bin/env bash
# Install nginx

#sudo apt-get update
#sudo apt-get -y install nginx
#sudo ufw allow 'Nginx HTTP'
#sudo echo "Hello, world!" > /var/www/html/index.html
#sudo service nginx restart

#!/usr/bin/env bash

# Update the package list and install Nginx
apt-get update -y
apt-get install nginx -y

# Create a simple HTML page with "Hello World!" message
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

# Start Nginx
sudo service nginx start
