#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration
echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 64820-web-01 54.159.2.30:80
        server 64820-web-02 54.236.47.245:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy
service haproxy restart
