#!/usr/bin/env bash
# script that makes a file, displays to infinity and beyond indefinitely
# Diplays i hate the kill command when receiving a SIGTERM signal
# Deletes the file created and terminaes itself  when receiving
# a SIGQUIT or SIGTERM signal

file=/var/run/myscript.pid
echo $$ > "$file"

while true
do
	echo "To infinity and beyond"
	sleep 2

	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm $file; exit' SIGQUIT
	trap 'echo I hate the kill command; rm $file; exit' SIGTERM
done
