#!/usr/bin/env bash
# script that stops 4-to_infinity_and_beyond process

# Get the pid of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# ends the infinite process
if [ -n "$id" ]
then
  kill -15 "$id"
fi
