#!/usr/bin/env bash
# prints the message infinity and beyond for
# eternity unless it is killed

trap "echo 'I am invincible!!!'" 15


# print the message to infinity
while true;
do
	echo "To infinity and beyond";
	sleep 2
done
