#!/usr/bin/env bash
# Displays 1 to 100 where "FizzBuzz" is displayed if the number is a multiple of 3 and 5,
# "Fizz" if the number is a multiple of 3, and "Buzz" if the
# number is a multiple of 5. Otherwise it displays the number

number=1

while [ $number -le 100 ]; do
      if [ $((number%5)) -eq 0 ] && [ $((number%3)) -eq 0 ]; then
	  echo "FizzBuzz"
      elif [ $((number%5)) -eq 0 ]; then
	  echo "Buzz"
      elif [ $((number%3)) -eq 0 ]; then
	  echo "Fizz"
      else
	  echo "$number"
      fi
      number=$((number+1))
done
