#!/usr/bin/env bash
# groups visitors by IP and HTTP status code, and
# Displays the IP and status code of an Apache log file

awk '{ printf "%s %s\n", $1, $9 }' "apache-access.log" | sort | uniq -c | sort -nr
