#!/usr/bin/env bash
# Displays numbers from 1 to 20 and the following
# "bad luck from China" in the 4th loop
# "bad luck from Japan" in the 9th loop
# "bad luck from Italy" in the 17th loop

luck=1

while [ $luck -le 20 ]
do
  echo "$luck"
  case $luck in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( luck++ ))
done
