#!/usr/bin/env bash
# install ufw firewall & set requirements

sudo apt-get update

# install UFW if not already installed
sudo apt-get install ufw

# enable UFW
sudo ufw enable

# set default policies
sudo ufw default deny incoming

sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status
